# Generated by Django 4.1.4 on 2023-06-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_airtravel'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtravel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
