# Generated by Django 4.1.4 on 2023-06-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_airtravel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtravel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
